version: '3.4'

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"