micronaut:
  application:
    name: partyPresence
redis:
  uri: redis://localhost
  io-thread-pool-size: 5
  computation-thread-pool-size: 4

io:
  github:
    paulushcgcj:
      presence:
        expiresIn: 10s
        database: 0
        keyspace: "io:github:paulushcgcj:uid"


