name: Project CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-test-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Code Validation
        run: mvn -B validate --file pom.xml
      - name: Code Compilation
        run: mvn -B clean compile --file pom.xml
      - name: Checkstyle
        run: mvn -B checkstyle:checkstyle -Dcheckstyle.skip=false --file pom.xml
      - name: Unit Tests
        run: mvn -B test --file pom.xml
      - name: Integration Tests
        run: mvn -B verify -P integration-test --file pom.xml
      - name: Code Coverage
        run: mvn -B clean verify -P all-tests coveralls:report --file pom.xml
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}