name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  artifact:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-test-

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build And Push Docker Image
        env:
          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE=`echo "${DOCKER_REGISTRY_URL}/${DOCKER_REPOSITORY_PATH}presence" | sed -e 's#//#/#' -e 's#^/##'`
          mvn deploy -Dpackaging=docker -Djib.docker.image=$DOCKER_IMAGE --no-transfer-progress

  validation:
    name: Validate Docker image
    runs-on: ubuntu-latest
    needs:
      - artifact
    if: startsWith(github.ref_name,'v')
    permissions:
      packages: write
      contents: read
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            paulushc/mn-presence
      - name: Image Scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: paulushc/mn-presence
          ignore-unfixed: true
          severity: CRITICAL
          format: 'sarif'
          output: 'docker-result.sarif'

      - name: Upload Security results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: "docker-result.sarif"